# -*- coding: utf-8 -*-
"""Devops Lab-01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQV1n9ijJ9Lxio-iGdbWVeXu2fU1cqBv
"""

from google.colab import drive
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Mount Drive
drive.mount('/content/drive')

# Load Datasets from Drive
train = pd.read_csv('/content/drive/MyDrive/Dataset/train.csv')
test = pd.read_csv('/content/drive/MyDrive/Dataset/test.csv')

# Clean & Drop Unused Columns
cols_to_drop = [c for c in [train.columns[0], 'id'] if c in train.columns]
train = train.drop(columns=cols_to_drop).dropna()
test = test.drop(columns=cols_to_drop).dropna()

# Select Features and Target
features = [
    'Online boarding', 'Inflight wifi service', 'Class', 'Type of Travel',
    'Inflight entertainment', 'Seat comfort', 'Leg room service',
    'Ease of Online booking', 'Customer Type', 'Flight Distance'
]
target = 'satisfaction'

X_train, y_train = train[features].copy(), train[target].copy()
X_test, y_test = test[features].copy(), test[target].copy()

# Categorical Feature Encoding
cat_cols = ['Class', 'Type of Travel', 'Customer Type']
for col in cat_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

# Target Encoding
le_target = LabelEncoder()
y_train = le_target.fit_transform(y_train)
y_test = le_target.transform(y_test)

print("Data loaded and preprocessed successfully!")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

rf = RandomForestClassifier(max_depth=7, n_estimators=150, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("=== PART A: RANDOM FOREST ===")
print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=15, random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

print("=== PART A: DECISION TREE ===")
print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))

#PART B New Model
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# =========================================================
# PART B: HISTOGRAM GRADIENT BOOSTING CLASSIFIER
# =========================================================
print("==================================================")
print("   PART B - NEW MODEL: HISTOGRAM GRADIENT BOOSTING")
print("==================================================")

# Initialize and train model
hgb = HistGradientBoostingClassifier(random_state=42)
hgb.fit(X_train, y_train)

# Predict on test set
y_pred_hgb = hgb.predict(X_test)

# Evaluate metrics
print("Accuracy :", accuracy_score(y_test, y_pred_hgb))
print("Precision:", precision_score(y_test, y_pred_hgb))
print("Recall   :", recall_score(y_test, y_pred_hgb))
print("F1 Score :", f1_score(y_test, y_pred_hgb))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_hgb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_hgb))